spring.application.name=message-service
server.port=8083

# Database connection settings for local development
spring.datasource.url=jdbc:mysql://localhost:3306/patient_journal_app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# Enable MySQL dialect for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Not sure if we will use JTA transactions, but I disable it for now
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/patient_app
spring.security.oath2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/patient_app/protocol/openid-connect/certs
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG