spring.application.name=JWT-Service
server.port=8081

spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/patient_app
# spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/patient_app/protocol/openid-connect/certs

keycloak.auth-server-url=http://keycloak-service:8080/realms/patient_app
keycloak.realm=patient_app
keycloak.resource=jwt-service
keycloak.public-client=false
keycloak.credentials.secret=3jy9YIl80kHpJVTbsIw588YP9IEouSXD
keycloak.bearer-only=true