spring.application.name=user-service
server.port=8082
logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=DEBUG

# Database connection settings for local development
spring.datasource.url=jdbc:mysql://localhost:3306/patient_journal_app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.properties.hibernate.format_sql=true
# Enable MySQL dialect for Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Not sure if we will use JTA transactions but i disable it for now
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/patient_app
spring.security.oath2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/patient_app/protocol/openid-connect/certs
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG

#jwt.secret=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGRR5EjI6sK7mNTodRpvt/tlMbDnopEIPKBJcGYVqh4f+S1K9l3GOnRTaXSt0GoaCmC+xbA6148Q2vAoZEQAyHXEhAnp9AXFcNe2Or3Ti31o44iF/fJ+wCOOM7eVvrX866+vRRZ61+8dz4L9FTCpzv3YU9g/2bGh/QMytTXfuSjdoXb3rBVIAJW1KzRB5ts89DW6BS5rWAkXTdoxwzcX2ogK6cHKx+upxlnAdmsBCFdSvzm34ZYSKHfkUf0UuhCKLnMEkwk6irqCcsmwk90Vp9IltDv2GPBDPvr7qDNBQh5+4U1A2dT5YDHyerc2ggnvE4iTlVJfzOXz9oQUggKy4wIDAQAB

keycloak.auth-server-url=http://keycloak-service:8080/realms/patient_app
keycloak.realm=patient_app
keycloak.resource=user-service
keycloak.public-client=false
keycloak.credentials.secret=OOyN40SRWK2sdctAsdjP3kvTGRQqwdDi
keycloak.bearer-only=true






