spring.application.name=user-service
server.port=${PORT:8080}

# Database connection settings for local development
spring.datasource.url=jdbc:postgresql://medical-app-db-postgres:5432/medical-app?user=admin&password=admin
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# OAuth2 Resource Server (Keycloak integration)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://wsjoden-kc.app.cloud.cbh.kth.se/realms/patient_app

# Debug logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG


