spring.application.name=user-service
server.port=${PORT:8080}

# Database connection settings for local development
spring.datasource.url=jdbc:mysql://medical-app-db:3306/medical-app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update    
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

# OAuth2 Resource Server (Keycloak integration)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://wsjoden-kc.app.cloud.cbh.kth.se/realms/patient_app

# Debug logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web=DEBUG


