quarkus.http.port=8086

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://medical-app-db-postgres:5432/medical-app
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, POST, PUT, DELETE, OPTIONS
quarkus.http.cors.headers=Content-Type, Authorization, X-Requested-With

# OIDC / JWT
quarkus.oidc.auth-server-url=https://wsjoden-kc.app.cloud.cbh.kth.se/realms/patient_app
quarkus.oidc.application-type=service
quarkus.oidc.token-audience=frontend,backend     
quarkus.oidc.roles.claim-path=role
quarkus.oidc.roles.source=access-token        

# Security
# quarkus.http.auth.permission.public.paths=/search/test
# quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.roles.paths=/*
quarkus.http.auth.permission.roles.policy=authenticated


# Logging
quarkus.log.category."io.quarkus.security".level=DEBUG
quarkus.log.category."io.quarkus".level=DEBUG
quarkus.log.level=DEBUG
