name: kthcloud-ci
"on":
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                registry: registry.cloud.cbh.kth.se
                username: ${{ secrets.DOCKER_USERNAME_USER_SERVICE }}
                password: ${{ secrets.DOCKER_PASSWORD_USER_SERVICE }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: ./backend/user_service
                file: ./backend/user_service/Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_TAG_USER_SERVICE }}
